#ifndef FILEENTRY_H
#define FILEENTRY_H
#include <QDebug>
#include <QString>
#include <QStringList>
#include <QDate>
#include <QTime>
#include <QTextCodec>
#include <QtGlobal>
#include <QSqlQuery>
#include<QMessageBox>
#include<QVariant>
#include<QSqlError>
/**
 * @brief Class constructed to get data from csv file generated by QR code scanner.
 It has special functions to simplify work with data entry from file.
 *
 * @class fileEntry fileentry.h "fileentry.h"
 */
class fileEntry
{

private:
    int idPoint; /**< Stores the point identificator */
    int vers; /**< Stores the special version value invented to prevent cheating */
    int devision; /**< Stores value of code devision*/
    QString name; /**< Not used */
    QDate cDate; /**< Date of point reading */
    QTime cTime; /**< Time of point reading */
    QString cPoint;/**< "Human" name of point */
    QString value; /**< Value of point in string representation */
    bool    itsOk; /**< Falue flag of point e.g. Are at this point any failures */
    QString cFailure; /**< Description of failure */
    QString description; /**< Additional information about point */
    QString CHKSUM; /**< Checksum of record */
    bool codeCorr; /**< Flag for show is this record correct*/
    bool isItWarned;
    bool isWarned();
public:
    fileEntry();
    bool fromString(QString String);
    int getId();
    int getVersion();
    QDate getDate();
    QTime getTime();
    QString getPointName();
    QString getValue();
    bool isOk();
    QString isntOkStr();
    QString getFailure();
    QString getDescription();
    bool checkSUM();
    float getValueNumber();
    QString getDimension();

    int getDivision();

    QString getString2Write();
    QString addHeader();
    QString getString2WriteHTML(QString dName);
    QString getString2WriteHTML();
    QString addHeaderHTML();

    QString getQueryToSend(int curId);
    int calcCode(QString str);
};

#endif // FILEENTRY_H
